"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '''$os$username$hostname$git_branch$conda$python$directory$character'''
right_format = """$cmd_duration"""

palette = 'foo'
[palettes.foo]
1st = '#8a4a64'
2nd = '#8e4959'
3rd = '#904a41'
com = '#837377'
hl = '#575992'
inf = '#575992'
suc = '#3d6838'
err = '#904a4a'

[os]
format = '[\[$symbol\] ](hl bold)'
disabled = false

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CachyOS = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
Nobara = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"

[username]
format = '[$user]($style)'
style_user = '3rd'
style_root = 'hl bold'
show_always = true
# aliases = { "corpuser034g" = "matchai" }

[hostname]
format = '[@$hostname$ssh_symbol](bold 1st)'
ssh_only = false
ssh_symbol = ""

[directory]
format = ' [$path]($style)[$read_only]($read_only_style) '
style = '3rd bold'
truncation_length = 3
truncation_symbol = '…/'
read_only = ''
read_only_style = 'err'

[git_branch]
format = '[\[](hl)[$symbol$branch(:$remote_branch)]($style)[\]](hl)'
style = '2nd'
symbol = ''
truncation_length = 6
truncation_symbol = '…'

[conda]
format = '[\[](hl)[$symbol$environment]($style)[\]](hl)'
symbol = ''
style = '2nd'
truncation_length = 1

[python]
format = '[\[](hl)[$symbol$version$pyenv_prefix(\($virtualenv\))]($style)[\]](hl)'
symbol = ''
style = '1st'
pyenv_prefix = '(pyenv)'
version_format = '${raw}'

[character]
success_symbol = "[❯](inf)"
error_symbol = "[❯](err bold)"
vimcmd_symbol = "[❮](inf)"

[cmd_duration]
format = '[$duration]($style)'
style = 'com'
min_time = 2_000
show_milliseconds = true
